version: '3'
services:
  code-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/home/coder/project
    environment:
      - PASSWORD=your_password_here
    container_name: vscode-server
