:table-caption: Table
:figure-caption: Figure

= Requirements definition of Tech Blog System - Version 1.0 - 2022-04-21

[.cover-project]
Tech Blog System:

[.cover-document]
Requirements Definition

[.cover-version]
Version 1.0

[.cover-date]
April 21st, 2022

[.cover-company]
Lorem Ipsum Co. Ltd.

[.cover-address]
4-3934, Sekihara minami, Nagaoka city, Niigata prefecture, Japan.

[.cover-tel]
TEL: +81-258-94-5233

[.cover-email]
E-mail: sales@exmaple.com



== Purpose and structure

The purpose of this document is to build consensus between the outsourcer and the outsourcee of this system development by defining the functional requirements of the system. The structure of this document is shown below.

. Purpose and structure
. List of pages
. Page layout
. Top page
. Article list page
. Article detail page
. Revision history



== List of pages

. Article list page
. Article detail Page



== Page layout

=== Content

. Header
.. Logo link
. Breadcrumb
. Main content
. Footer
.. Copyright

=== Behavior

. When the user clicks the logo link, the system displays the top page.

[plantuml]
----
class Animal {
  run()
}

class Cat extends Animal {
}
----


== Article list page

=== Content

. Main content
.. List navigation
... Article links
.... Posted date
.... Title

=== Behavior

. When the user clicks an article link, the system displays the article detail page.


== Article detail page

=== Content

. Main content
.. Menu
... Back link
.. Title
.. Posted date
.. Text
.. Related posts navigation
... Article links
.... Posted date
.... Title

=== Behavior

. When the user clicks the back link, the system displays the article list page.
. When the user clicks an article link, the system displays the article detail page.



== Revision history

The revision history of this document is shown in the table below.

.Revision history
[cols="1,3,3,2"]
|===
| Version | Date | Comment | Author

| 1.0 | April 21st, 2022 | The first edition | T. Susukida
|===


== Further

text

[plantuml]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
----